description: Service
properties:
- category:
    description: Is it a customer facing or resource facing service.
    type: string
- description:
    description: Free-text description of the service.
    type: string
- endDate:
    description: (DateTime). Date when the service ends.
    format: date-time
    type: string
- feature:
    description: list of features (Feature [*]). list of feature associated with this
      service.
    items:
      $ref: '#/components/schemas/feature'
    type: array
- hasStarted:
    description: If TRUE, this Service has already been started.
    type: boolean
- href:
    description: Reference of the service
    type: string
- id:
    description: Unique identifier of the service.
    type: string
- isBundle:
    description: If true, the service is a ServiceBundle which regroup a service hierachy.
      If false, the service is a 'atomic' service (hierachy leaf).
    type: boolean
- isServiceEnabled:
    description: If FALSE and hasStarted is FALSE, this particular Service has NOT
      been enabled for use - if FALSE and hasStarted is TRUE then the service has
      failed.
    type: boolean
- isStateful:
    description: If TRUE, this Service can be changed without affecting any other
      services.
    type: boolean
- name:
    description: Name of the service.
    type: string
- note:
    description: list of notes (Note [*]). list of notes made on this service.
    items:
      $ref: '#/components/schemas/note'
    type: array
- place:
    description: list of related place ref or values (RelatedPlaceRefOrValue [*]).
      list of places (Place [*]). Used to define a place useful for the service (for
      example a geographical place whre the service is installed).
    items:
      $ref: '#/components/schemas/place'
    type: array
- relatedEntity:
    description: list of related entity ref or values (RelatedEntityRefOrValue [*]).
      list of related entity in relationship with this service.
    items:
      $ref: '#/components/schemas/relatedEntity'
    type: array
- relatedParty:
    description: list of related parties (RelatedParty [*]). list of related party
      references (RelatedParty [*]). A related party defines party or party role linked
      to a specific entity.
    items:
      $ref: '#/components/schemas/relatedParty'
    type: array
- serviceCharacteristic:
    description: list of characteristics (Characteristic [*]). list of characteristics
      that characterize this service (ServiceCharacteristic [*]).
    items:
      $ref: '#/components/schemas/serviceCharacteristic'
    type: array
- serviceDate:
    description: Date when the service was created (whatever its status).
    type: string
- serviceOrderItem:
    description: list of related service order items (RelatedServiceOrderItem [*]).
      list of service order items related to this service
    items:
      $ref: '#/components/schemas/serviceOrderItem'
    type: array
- serviceRelationship:
    description: list of service relationships (ServiceRelationship [*]). list of
      service relationships (ServiceRelationship [*]). Describes links with other
      service(s) in the inventory.
    items:
      $ref: '#/components/schemas/serviceRelationship'
    type: array
- serviceSpecification:
    description: service specification reference (ServiceSpecificationRef). The specification
      from which this service was instantiated.
    items:
      $ref: '#/components/schemas/serviceSpecification'
    type: array
- serviceType:
    description: Business type of the service.
    type: string
- startDate:
    description: (DateTime). Date when the service starts.
    format: date-time
    type: string
- startMode:
    description: 'This attribute is an enumerated integer that indicates how the Service
      is started, such as: 0: Unknown; 1: Automatically by the managed environment;
      2: Automatically by the owning device; 3: Manually by the Provider of the Service;
      4: Manually by a Customer of the Provider; 5: Any of the above.'
    type: string
- state:
    description: (ServiceStateType). The life cycle state of the service, such as
      designed, reserved, active, etc...
    items:
      $ref: '#/components/schemas/state'
    type: array
- supportingResource:
    description: 'list of resource references (ResourceRef [*]). list of supporting
      resources (SupportingResource [*]).Note: only Service of type RFS can be associated
      with Resources.'
    items:
      $ref: '#/components/schemas/supportingResource'
    type: array
- supportingService:
    description: list of service ref or values (ServiceRefOrValue [*]). list of supporting
      services (SupportingService [*]). A collection of services that support this
      service (bundling, link CFS to RFS).
    items:
      $ref: '#/components/schemas/supportingService'
    type: array
type: object
